### ISSUE TITLE
Dúvidas na implementação do greatPrimeFactor função validateNumber

### ISSUE THREAD

**Issue by RafaelMedeirosGomes** [samuel-constantino/desafio-tecnico-zapt-tech#2]
https://github.com/samuel-constantino/algorithms/blob/28bca41004eaf084620a977acef6ebac308ac07f/src/challenges/node/greatPrimeFactor.js#L9-L13
Opa, tudo bem Samuel? Não entendi muito bem essa parte, consegue me ajudar? Pelo que entendi essa função retorna um booleano -> caso o número seja par, e retorna -1 caso o número seja impar. E o objetivo dela seria já, de cara, remover metade das verificações de números (todos os pares) do código, é isso mesmo?

**Comment by RafaelMedeirosGomes** [comment]
Dado o que entendi da função validateNumber e sobre os valores possíveis para a variável currentDivider:
https://github.com/samuel-constantino/algorithms/blob/28bca41004eaf084620a977acef6ebac308ac07f/src/challenges/node/greatPrimeFactor.js#L34-L45
aqui nessa parte abaixo:
https://github.com/samuel-constantino/algorithms/blob/28bca41004eaf084620a977acef6ebac308ac07f/src/challenges/node/greatPrimeFactor.js#L15-L17
Conseguiriamos substituir por:
```javascript
if (n % 2 === 0) return n === 2;
```
faz sentido?

**Comment by samuel-constantino** [comment]
Perfeito, faz todo sentido.
Essa validação do input estava me incomodando, pois parecia desnecessariamente complexa.
Obrigado pela contribuição, fiz essa alteração no código.
